### ISSUE TITLE
Automatic module name missing in the implementation JAR

### ISSUE THREAD

**Issue by jeffmorin** [jakartaee/tags#246]
Hi everyone:

It's impossible to include both the API and the implementation of JSTL in their current form in a modularized project (i.e. with module-info.java files).

The API is already fully modularized with `jakarta.servlet.jsp.jstl` as a module name in its `module-info.java` file. This is fine.

The implementation, however, is not modularized and has no automatic module name, which leaves no choice other than deducing the module name from the generated JAR name. But this JAR name, after being stripped from the version number according to the automatic module naming rules, is precisely `jakarta.servlet.jsp.jstl`, which is the same as the API module name above.

See the problem? This creates a conflict, as both JARs happen to have the same module name and therefore cannot be used together in any modularized project.

If the development team is not willing to add a `module-info.java` file right away, a simple solution consists in adding an `Automatic-Module-Name` entry in the `maven-jar-plugin` configuration:

```
<manifestEntries>
  ...
  <Automatic-Module-Name>org.apache.servlet.jsp.jstl</Automatic-Module-Name>
</manifestEntries>
```

where the automatic module name _must_ be different from `jakarta.servlet.jsp.jstl`.

I used `org.apache.servlet.jsp.jstl` to mimic what was done with Jakarta EL (`jakarta.el`for the API, `com.sun.el` for the implementation), but any other suitable module name can be chosen instead.

I tried to file this fix request through a pull request from the `master` branch, only to find out that it doesn't contain the implementation. If I must file a pull request, which branch should I start from?

Thanks.

**Comment by arjantijms** [comment]
The implementation moved to the WaSP project: https://github.com/eclipse-ee4j/wasp

See also https://github.com/jakartaee/tags/issues/146

**Comment by arjantijms** [comment]
> com.sun.el for the implementation

The automatic module name for the Expression Language implementation is actually `org.glassfish.expressly`. See:

https://github.com/eclipse-ee4j/expressly/blob/master/pom.xml#L173

**Comment by jeffmorin** [comment]
Looks like I didn't find the right location when I searched for the WaSP project... Many thanks Arjan, I'll look there.

**Comment by jeffmorin** [comment]
Finally, just what the doctor ordered... Thanks again!
